AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'bin/*'

Metrics/MethodLength:
  Max: 400
  Exclude:
    - 'spec/**/*'
    - 'lib/open_api_import/open_api_import.rb'

Metrics/AbcSize:
  Max: 500
  Exclude:
    - 'spec/**/*'
    - 'lib/open_api_import/open_api_import.rb'

Metrics/CyclomaticComplexity:
  Max: 80
  Exclude:
    - 'lib/open_api_import/open_api_import.rb'

Metrics/PerceivedComplexity:
  Max: 80
  Exclude:
    - 'lib/open_api_import/open_api_import.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'
    - 'bin/open_api_import'
    - 'lib/open_api_import/open_api_import.rb'
    - 'lib/open_api_import/get_examples.rb'

Metrics/ClassLength:
  Max: 800

Layout/LineLength:
  Max: 200

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/MethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Next:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/UnreachableLoop:
  Enabled: false

Lint/EmptyFile:
  Exclude:
    - 'spec/open_api_import/utils/open_api_import_utils_spec.rb'

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Security/Eval:
  Exclude:
    - 'spec/**/*'
